### ISSUE TITLE
Route Drawing in Java API / eeGeo Routing Service

### ISSUE THREAD

**Issue by UmarMajeed-Rana** [wrld3d/android-api#1]
Hi while exploring java api I couldn't find ways to draw routes in eeGeo world. Can you guide me how i can achieve that using Java API ?

**Comment by jlunderwood** [comment]
Thanks for your interest in eeGeo maps.

The Android Java API is recently released - so far, it supports the core features to display and interact with a map. At the minute, it does not support route drawing.  

We'll be working on exposing more features from our C++ SDK over the coming months. It's useful to know the features that you are most interested in - we'll keep these in mind when prioritising our work.

**Comment by UmarMajeed-Rana** [comment]
@jlunderwood thanks for swift response. Our use case required indoor navigation. I think it would be really helpful if you can prioritise features related to this use case. Is there any plan of releasing source code responsible for Native Binding so that one who are interested in features not exposed in java API can implement those features using the work u guys have already done.

**Comment by jlunderwood** [comment]
The source code for the Android Java API is available at https://github.com/eegeo/android-api. This includes bindings to the C++ layer. The C++ library does support route drawing and the eeGeo routing service (https://github.com/eegeo/eegeo-routing-api) -- you can see examples at https://github.com/eegeo/eegeo-sdk-samples/tree/master/src/Examples/RouteDrawing and https://github.com/eegeo/eegeo-sdk-samples/tree/master/src/Examples/RoutingService

I hope this helps in the short term.

**Comment by UmarMajeed-Rana** [comment]
@jlunderwood Only Cpp files i can see are jnimain.h and jnimain.cpp. I can access reference to EegeoWorld there . There is no source for binding of e.g MarkerApi. I will try to take inspiration from jnimain.cpp and write a binding for route drawing

**Comment by jlunderwood** [comment]
The rest of the native binding points are in the main C++ library. The download script installs the headers to libs/eegeo/, underneath sdk/src/main/cpp.  You may wish to look at the eegeo-api, eegeo-api-host, and especially eegeo-api-host/Android directories.  As you noticed, you can get a reference to EegeoWorld from the AndroidApiRunner via the IEegeoApiHostModule.

Please note that these API points are under active development and may change as we work on making our APIs easier to use.  I can't guarantee that it will be possible for you to add route drawing using the current interface, even with access to the EegeoWorld object.

**Comment by tim-jenks** [comment]
This is in progress

**Comment by malcolm-brown** [comment]
The [RouteView ](https://github.com/wrld3d/android-api/blob/master/sdk/src/main/java/com/eegeo/mapapi/widgets/RouteView.java)widget now exists for this purpose, and the [Routing Service](https://github.com/wrld3d/android-api/blob/master/sdk/src/main/java/com/eegeo/mapapi/services/routing/RoutingService.java) for fetching the routes.

Closing this issue.
