### ISSUE TITLE
Indoor floor slider is not visible after resume

### ISSUE THREAD

**Issue by jraanamo** [wrld3d/android-api#2]
When entering indoor view, floor slider is shown on the right side of the screen. Switching to another app and resuming back to the indoor view hides the floor slider. 

Using SDK 0.0.324 on Android 7.1.2

**Comment by tim-jenks** [comment]
Thanks @jraanamo will resolve for next Android API release

**Comment by jonty-dawson** [comment]
Tracking internally with MPLY-9029

**Comment by tim-jenks** [comment]
This is marked as resolved internally
