### ISSUE TITLE
Domain service exists for wrld pois

### ISSUE THREAD

**Issue by tim-jenks** [wrld3d/android-api#3]
A domain service, example and documentation exists for fetching and applying a wrld pois:

https://github.com/wrld3d/wrld-poi-api

**Comment by malcolm-brown** [comment]
This exists as [PoiService](https://github.com/wrld3d/android-api/blob/master/sdk/src/main/java/com/eegeo/mapapi/services/poi/PoiService.java). Examples of usage [Here](https://wrld3d.com/android/latest/docs/examples/search-for-pois/).
