### ISSUE TITLE
Domain service exists for wrld mapscenes

### ISSUE THREAD

**Issue by tim-jenks** [wrld3d/android-api#4]
A domain service, example and documentation exists for fetching and applying a wrld mapscene:

https://github.com/wrld3d/wrld-mapscene-api

**Comment by malcolm-brown** [comment]
This exists as [MapsceneService](https://github.com/wrld3d/android-api/blob/master/sdk/src/main/java/com/eegeo/mapapi/services/mapscene/MapsceneService.java).

Examples of usage are [Here](https://wrld3d.com/android/latest/docs/examples/load-mapscene/).
