### ISSUE TITLE
Marker Label Position

### ISSUE THREAD

**Issue by yann40fr** [wrld3d/android-api#5]
Hi all,

Great api but is there any way to set the position of marker label ?

Best regards,

![screenshot_20171130-145855](https://user-images.githubusercontent.com/34131930/33434406-7d541d18-d5df-11e7-8390-a94babd7a623.png)

**Comment by jonty-dawson** [comment]
Hi - 
You can set the position property of the MarkerOptions when creating a marker, see example here:
https://wrld3d.com/android/latest/docs/examples/create-a-marker/
Or you can change the position of a Marker after creation like this:
https://wrld3d.com/android/latest/docs/examples/change-location-of-a-marker/

From you screenshot though, it looks like you have the label text overlapping the icon - not sure how that is occurring. Could you provide a code snippet for how you are creating that marker please?

**Comment by yann40fr** [comment]
Hi,

Thanks for this fast answer but that's ok for the marker position but not for the label position around marker :/

Here a code snippet of my app :

        @Override
        public void onProgressUpdate(Portal... values) {
            final Portal portal = values[0];

            MarkerOptions markerOptions = new MarkerOptions();

            markerOptions.labelText(portal.getName());
            markerOptions.position(new LatLng(portal.getLat(), portal.getLon()));

            markerOptions.userData(POI.Type.PORTAL.toString());
            markerOptions.iconKey(IconKey.LODGE.toString());

            // final Marker portalMarker = mMap.addMarker(markerOptions);
            mMap.addMarker(markerOptions);

            super.onProgressUpdate(values);
        }

**Comment by yann40fr** [comment]
Hi,

The overlapp issue seem to be disappear without any extra manipulations .... but my first question about the label position around the marker is always here ....A label above or below a marker would be great.

A custom marker would also be very nice (custom style perhaps ?)

Best regards,

![screenshot_20171130-154005](https://user-images.githubusercontent.com/34131930/33436758-342f74c8-d5e6-11e7-8683-b55823b31dc0.png)

**Comment by jonty-dawson** [comment]
Thanks for the update - I'm not sure what caused the label overlapping the icon, but if it seems resolved now we probably won't investigate further.

For customizing the relative anchor points of Marker text label and icon, unfortunately we don't yet have a way to do this via the API.

Similarly for using custom icons, there isn't currently a simple means of doing this. However, if you really need this, it might be possible to alter some assets included in the SDK to acheive what you want.

All icon images are included in an image asset here:
https://github.com/wrld3d/android-api/blob/master/sdk/src/main/assets/pin_sheet_0.png
(and at multiple resolutions for use on different devices in similarly named files same folder).

This json file has entries specifies a rectangle for each of the icons in the above image assets, and associates with a string key:
https://github.com/wrld3d/android-api/blob/master/sdk/src/main/assets/pin_sheet.json

For example the icon with key "lodge" is here:
https://github.com/wrld3d/android-api/blob/master/sdk/src/main/assets/pin_sheet.json#L686

The above links are to source files, but these end up in a corresponding file inside the distributed wrld-android-sdk.aar, under ./assets. With care, you may be able to hand-edit these to add your own icon - but this approach probably isn't viable if you need lots of custom icons.

**Comment by yann40fr** [comment]
Thanks for your answer, i'll keep an eye on the next update (or the next of the next ;) )...
