### ISSUE TITLE
Multiple views not working

### ISSUE THREAD

**Issue by akkravikumar** [wrld3d/android-api#8]
I tried this code also https://docs.eegeo.com/android/latest/docs/examples/position-multiple-views-on-map/

but i won't work. The view is displayed one at a time. cant view the multiple views.

should i add anything in xml for viewing multiple view.

Could you resolve this issue

**Comment by jlunderwood** [comment]
An updated example is available at https://github.com/wrld3d/android-api-samples/issues/2.  The online docs will be fixed as soon as possible.
